### PR TITLE
Fix a bug and clean up code

### PR DESCRIPTION
**Pull request by ruhatch**
- Fixed a bug where functions would be duplicated in the anti-unification (due to tails)
- Cleaned up the code with some formatting and a few refactorings
- Updated custom type test (that for some reason wanted duplicate functions!)

### CODE REVIEW

**Comment by frankshearar** [comment]
Sorry about the slow response - I was on holiday.

I'm broadly happy with the review (if I was nitpicking I'd say I'd have preferred to see a cleanup/format review separately from the bugfix, but that's fine).

I rather like the decomposition of possiblyUnifiable. Nice one!

However, `foreach` reads too much like the C# keyword. I guess it's there so the reader doesn't have to go hunting for the `xs` usage? (Because it otherwise just looks like map  + flip). If so, why not say

````fsharp
let heads xs =
    xs |>
    map (function
         | Function (name, t::ts) -> t
         | unrecognised           -> failwith (sprintf "heads can only process a Function, not %A" unrecognised))
````

which gives the xs due prominence?

Now to the meat of the change. If I understand correctly, the core change is replacing

````fsharp
| Function (name, t::ts) -> Function (name, [t])
````

in `heads` with

````fsharp
| Function (name, t::ts) -> t
````

which does indeed seem like a bug: the original returns, given f(t1::tn), f(t1), not t1. And I should have noticed that the test data looked a bit sketchy.

So how about you remove the `foreach` guy, and then what I can do maybe is take your branch, add a few commits on the end (for example, I prefer function comments to be full sentences ending in full stops), and merge it in?

**Comment by frankshearar** [comment]
Also, a huge thank you for taking the time and trouble to read my awful code and make it better!

**Comment by ruhatch** [comment]
Hi Frank,

Thanks for getting back to me. Unfortunately I did this work while I was
interning at Microsoft Research over the summer and I no longer have access
to the development machine. Therefore I am no longer able to build this
code, because I don't have Visual Studio, F#, etc. on my personal laptop.
Please feel free to take the changes and modify them however you like.

Kind regards,

Rupert

**Comment by frankshearar** [comment]
Thanks very much, Rupert!

**Pull request merged**
